export const BRAND_CONFIG = {
  'explorando-experiencias': {
    name: 'Explorando Experiencias',
    short: 'Explorando Experiencias',
    tagline: 'Viajes, eventos y comunidades para explorar Perú y el mundo',
    gradient: 'from-coral-500 to-coral-700',
    accent: 'coral',
    text: 'text-coral-600',
    bg: 'bg-coral-500',
    bgLight: 'bg-coral-50',
    border: 'border-coral-200',
    ring: 'ring-coral-400',
    chipBg: 'bg-coral-100',
    chipText: 'text-coral-700',
    instagram: 'https://www.instagram.com/explorando_rutas_/',
    whatsapp: 'https://wa.me/51999999999',
  },
  'viajes-para-solteros': {
    name: 'Viajes para Solteros Perú',
    short: 'Viajes para Solteros',
    tagline: 'Viajes y eventos para conectar, conocer nuevos destinos y compartir experiencias',
    gradient: 'from-turquoise-500 to-turquoise-700',
    accent: 'turquoise',
    text: 'text-turquoise-600',
    bg: 'bg-turquoise-500',
    bgLight: 'bg-turquoise-50',
    border: 'border-turquoise-200',
    ring: 'ring-turquoise-400',
    chipBg: 'bg-turquoise-100',
    chipText: 'text-turquoise-700',
    instagram: 'https://www.instagram.com/viajesparasolteros.lima/',
    whatsapp: 'https://wa.me/51999999999',
  },
  'club-social-solteros': {
    name: 'Club Social de Solteros Perú',
    short: 'Club Social',
    tagline: 'Una comunidad para disfrutar tu soltería de forma segura y divertida',
    gradient: 'from-plum-500 to-plum-700',
    accent: 'plum',
    text: 'text-plum-600',
    bg: 'bg-plum-500',
    bgLight: 'bg-plum-50',
    border: 'border-plum-200',
    ring: 'ring-plum-400',
    chipBg: 'bg-plum-100',
    chipText: 'text-plum-700',
    instagram: 'https://www.instagram.com/clubsocialsolterosperu/',
    whatsapp: 'https://wa.me/51999999999',
  },
} as const;

export type BrandSlug = keyof typeof BRAND_CONFIG;
